[package]
name = "wordsearch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.19"
rayon = "1.6.0"

[[bin]]
name = "wordsearch"
path = "src/main.rs"
